# Travis-CI Build for Hangfire
# see travis-ci.org for details

language: csharp
sudo: required
dist: trusty

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      os: linux
    - dotnet: 1.0.1
      mono: none
      os: osx
    - mono: latest
      os: linux
    - mono: latest
      os: osx

# Only watch the master branch.
branches:
  only:
    - master
    - dev

# Run the build script
script:
  - if hash mono 2>/dev/null; 
    then 
        chmod +x .nuget/NuGet.exe;
        travis_retry nuget install .nuget/packages.config -OutputDirectory packages;
        travis_retry nuget restore Hangfire.Mono.sln;
        xbuild /p:Configuration=Release /verbosity:minimal Hangfire.Mono.sln;
        mono ./packages/xunit.runner.console.2.2.0-beta2-build3300/tools/xunit.console.exe ./tests/Hangfire.Core.Tests/bin/Release/Hangfire.Core.Tests.dll -verbose;
    else
        travis_retry dotnet restore Hangfire.sln --disable-parallel; 
        dotnet test tests/Hangfire.Core.Tests -verbose;
    fi

notifications:
  slack:
    secure: LZuLPI1Cj9DgNAtFsZ/zk1fWBDS2PTHHIjvtCV3Fa9qNajzna2qR6Ui3sM/FQirvoXp0JHAqNYkFDI216YativqabWXZp6dQgw3u64bdlc1IWxQ4C6XHpp8WVe1wsNi19vfwKVHfvaNXpvNp9OGHXkmoTS74arRtPhpzSXO/IXw=
    on_success: change
    on_failure: always
