# Travis-CI Build for Hangfire
# see travis-ci.org for details

language: csharp
sudo: required
dist: trusty

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      os: linux
      env: NET_PLATFORM=netcore
    - dotnet: 1.0.0-preview2-003121
      mono: none
      os: osx
      env: NET_PLATFORM=netcore
    - mono: latest
      os: linux
      env: NET_PLATFORM=mono
    - mono: latest
      os: osx
      env: NET_PLATFORM=mono

env:  
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

# Only watch the master branch.
branches:
  only:
    - master
    - dev

# Make sure build dependencies are installed.
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

# Run the build script
script:
  - if test "$NET_PLATFORM" == "mono"; 
    then 
        chmod +x .nuget/NuGet.exe;
        travis_retry nuget install .nuget/packages.config -OutputDirectory packages;
        travis_retry nuget restore Hangfire.Mono.sln;
        xbuild /p:Configuration=Release /verbosity:minimal Hangfire.Mono.sln;
        mono ./packages/xunit.runner.console.2.2.0-beta2-build3300/tools/xunit.console.exe ./tests/Hangfire.Core.Tests/bin/Release/Hangfire.Core.Tests.dll -verbose;
    fi
  - if test "$NET_PLATFORM" == "netcore"; 
    then 
        travis_retry dotnet restore --disable-parallel; 
        dotnet test tests/Hangfire.Core.Tests -verbose;
    fi

notifications:
  slack:
    secure: LZuLPI1Cj9DgNAtFsZ/zk1fWBDS2PTHHIjvtCV3Fa9qNajzna2qR6Ui3sM/FQirvoXp0JHAqNYkFDI216YativqabWXZp6dQgw3u64bdlc1IWxQ4C6XHpp8WVe1wsNi19vfwKVHfvaNXpvNp9OGHXkmoTS74arRtPhpzSXO/IXw=
    on_success: change
    on_failure: always
